spring.application.name=Boot-ConfigurationPropertiesTask3
cart.user=Anita Sharma
cart.totalAmount=4500

cart.quantities=1,2,1,3

cart.items=Laptop Bag,Mouse,Notebook,Pen Pack

cart.coupons=NEW20,FESTIVE10,LOYAL5

cart.prices.LaptopBag=1200
cart.prices.Mouse=600
cart.prices.Notebook=150
cart.prices.PenPack=100
